"""membuat model data member otomax

Revision ID: e9274984b9b2
Revises: 
Create Date: 2025-08-17 08:49:27.792870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9274984b9b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('memberid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=False),
    sa.Column('report_url', sa.String(), nullable=False),
    sa.Column('hash_pin', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_nosign', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('memberid')
    )
    op.create_index(op.f('ix_members_memberid'), 'members', ['memberid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_memberid'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
